module.exports={
    module:{
        rule:[
        {
            test:/\.css$/,
            use:['style-loader','css-loader'],
        },
        {
            test:/\.svg$/,
            use:['svg-loader'],
        },
    ],
    },
};